import {createMuiTheme} from '@material-ui/core';

export const colors = {
  darkgreen: '#39603D',
  lightblue: '#A3BCB6',
  darkgrey: '#3C403D',
  lightgrey: '#DADED4',
};

export const theme = createMuiTheme({
  palette: {
    primary: {
      main: colors.darkgrey,
    },
    secondary: {
      main: colors.lightblue,
    },
  },
})
  ;

export type Values = {
  A: string,
  B: string,
  C: string,
  D: string,
  E: string,
  F: string,
  G: string,
  H: string,
  I1: string,
  I2?: string,
  I3?: string,
  I4?: string,
  I5?: string,
  I6?: string,
  I7?: string,
  I8?: string,
  J1?: string,
  J2?: string,
  J3?: string,
  J4?: string,
  J5?: string,
  J6?: string,
  J7?: string,
  J8?: string,
  K1?: string,
  K2?: string,
  K3?: string,
  K4?: string,
  K5?: string,
  K6?: string,
  K7?: string,
  K8?: string,
  L?: string,
  M?: string,
  N: string,
  O: string,
  P?: string,
  Q: string,
  R: string,
  S?: string
  separator: string,
}

export const keys = {
  separator: '*',
  A: 'NIF do emitente',
  B: 'NIF do adquirente',
  C: 'País do adquirente',
  D: 'Tipo de documento',
  E: 'Estado do documento',
  F: 'Data do documento',
  G: 'Identificação única do documento',
  H: 'ATCUD',
  I1: 'Espaço fiscal',
  I2: 'Base tributável isenta de IVA',
  I3: 'Base tributável de IVA à taxa reduzida',
  I4: 'Total de IVA à taxa reduzida',
  I5: 'Base tributável de IVA à taxa intermédia',
  I6: 'Total de IVA à taxa intermédia',
  I7: 'Base tributável de IVA à taxa normal',
  I8: 'Total de IVA à taxa normal',
  J1: 'Espaço fiscal',
  J2: 'Base tributável isenta de IVA',
  J3: 'Base tributável de IVA à taxa reduzida',
  J4: 'Total de IVA à taxa reduzida',
  J5: 'Base tributável de IVA à taxa intermédia',
  J6: 'Total de IVA à taxa intermédia',
  J7: 'Base tributável de IVA à taxa normal',
  J8: 'Total de IVA à taxa normal',
  K1: 'Espaço fiscal',
  K2: 'Base tributável isenta de IVA',
  K3: 'Base tributável de IVA à taxa reduzida',
  K4: 'Total de IVA à taxa reduzida',
  K5: 'Base tributável de IVA à taxa intermédia',
  K6: 'Total de IVA à taxa intermédia',
  K7: 'Base tributável de IVA à taxa normal',
  K8: 'Total de IVA à taxa normal',
  L: 'Não sujeito/ não tributável em IVA/ outras situações',
  M: 'Imposto do Selo',
  N: 'Total de impostos',
  O: 'Total do documento com impostos',
  P: 'Retenções na fonte',
  Q: '4 carateres do Hash',
  R: 'Nº do certificado',
  S: 'Outras informações',
};
